"""
core/color_classify.py — Android port
=========================================
Ported from image_measure_tool_color.py's classify_color_group().
Desktop version used a module-level `_svg_color_palette` global set by
make_colors()/load_svg(); refactored here to take the palette as an
explicit parameter — cleaner for a Kivy app where the SVG picker screen
owns that state rather than a global.
"""

import math


def rgb_to_folder_key(r, g, b):
    """(255, 0, 0) -> '255_0_0' — matches the recolored image subfolder name."""
    return f"{r}_{g}_{b}"


def classify_color_group(r, g, b, svg_color_palette=None):
    """Map a fill colour to (img_number, desaturation, pensize).

    COLOR MODE (svg_color_palette provided/non-empty): img_number is an
    RGB folder key like '255_0_0' matching the recolored image subfolder
    generated by make_colors().

    LEGACY MODE (no palette): falls back to random_light/midtone/dark
    based on nearest canonical colour.
    """
    if svg_color_palette:
        best_dist = float("inf")
        best_key = None
        for (pr, pg, pb) in svg_color_palette:
            dist = math.sqrt((r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2)
            if dist < best_dist:
                best_dist = dist
                best_key = rgb_to_folder_key(pr, pg, pb)
        return (best_key, 0, 8)

    COLOURS = [
        ((255, 255, 0), "random_light", 0, 2),
        ((10, 200, 10), "random_light", 120, 2),
        ((10, 10, 255), "random_midtone", 0, 2),
        ((150, 0, 200), "random_midtone", 120, 2),
        ((255, 10, 10), "random_dark", 0, 2),
        ((40, 40, 40), "random_dark", 120, 2),
    ]
    best_dist, best_entry = float("inf"), COLOURS[0]
    for canon_rgb, img_num, desat, ps in COLOURS:
        dist = math.sqrt((r - canon_rgb[0]) ** 2 +
                          (g - canon_rgb[1]) ** 2 +
                          (b - canon_rgb[2]) ** 2)
        if dist < best_dist:
            best_dist, best_entry = dist, (canon_rgb, img_num, desat, ps)
    _, img_num, desat, ps = best_entry
    return (img_num, desat, ps)
