"""
core/pv_pipeline.py — Android port of pv.py
================================================
Renders a still image from a list of polygons using the PIL-based drawer.

Rebuilt to be generic: on the desktop, pv.py was a template you'd hand-edit,
pasting a fresh block of draw_polygon_img(...) calls (generated by
image_measure_tool_color.py's SVG picker) in before every run. Here that
becomes an explicit `polygons` parameter — a list of dicts with the same
fields each draw_polygon_img(...) call used to carry — instead of editing
source code per-artwork. Falls back to a bundled sample artwork if none
is supplied, for quick testing.

turtle.Turtle()/turtle.Screen() are replaced with no-op stand-ins
(turtle_stub.py) — safe because finalize_and_save() never reads the
screen object, and the saved PNG comes entirely from the PIL-based
drawer, not anything actually drawn on a turtle canvas.
"""

import os

from core.turtle_stub import TurtleStub, ScreenStub
from core.polygon_render import setup_image_drawer
from core.sample_artwork import PV_SAMPLE_POLYGONS

W = 900
H = 900
LOGICAL_W = 360
LOGICAL_H = 360
UPSCALE = 1
BG_COLOR = (255, 255, 255)


def run(image_lib_path, output_dir, polygons=None, progress_cb=None):
    """
    image_lib_path : folder of R_G_B-keyed reference/pattern images
                      (as generated by core/make_colors.py)
    output_dir     : folder to save output_img.png into
    polygons       : list of dicts: {points, img_number, pen_color,
                      pensize, desaturation} — one per shape, in the order
                      they should be drawn (background/large shapes first).
                      Falls back to a bundled sample artwork if omitted.
    progress_cb    : optional callable(str) for on-screen status updates
    Returns the saved output file path.
    """
    def report(msg):
        if progress_cb:
            progress_cb(msg)
        print(msg)

    if polygons is None:
        report("No polygons supplied — using bundled sample artwork.")
        polygons = PV_SAMPLE_POLYGONS

    os.makedirs(output_dir, exist_ok=True)

    t = TurtleStub()
    s = ScreenStub()
    s.colormode(255)
    s.setup(W, H)
    s.bgcolor(BG_COLOR)
    s.tracer(0, 0)
    t.pensize(1)
    s.setworldcoordinates(-LOGICAL_W / 2, -LOGICAL_H / 2, LOGICAL_W / 2, LOGICAL_H / 2)

    report("Setting up drawer…")
    drawer = setup_image_drawer(
        image_lib_path=image_lib_path,
        canvas_w=W, canvas_h=H,
        logical_w=LOGICAL_W, logical_h=LOGICAL_H
    )

    for i, poly in enumerate(polygons, 1):
        if i % 10 == 0 or i == len(polygons):
            report(f"Registering shape {i}/{len(polygons)}")
        drawer.register_polygon(
            poly['points'],
            poly['img_number'],
            poly.get('pen_color', (45, 45, 48)),
            poly.get('pensize', 8),
            poly.get('desaturation', 0),
        )

    s.update()

    report("Rendering final image…")
    file_path = os.path.join(output_dir, "output_img.png")
    drawer.finalize_and_save(s, file_path, upscale=UPSCALE)
    report(f"Saved: {file_path}")
    return file_path
